# Menus
menu:
    Home: /
    # Delete this row if you don't want categories in your header nav bar
    About: /about/index.html
    pt: /pt/index.html
    toyproject: /toyproject/index.html
    Categories:

# Customize
customize:
    theme_color: '#0069ba'
    highlight: androidstudio
    sidebar: left # sidebar position, options: left, right
    thumbnail: true # enable posts thumbnail, options: true, false
    favicon: # path to favicon
    social_links: # for more icons, please see http://fontawesome.io/icons/#brand
        facebook: https://www.facebook.com/hanghui.i
        github: https://github.com/javarouka
        rss: /atom.xml

# Widgets
widgets:
    - category
    # - archive
    - recent_posts
    - tag
# - tagcloud
    - links

# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false

# Comment
comment:
    disqus: https-javarouka-github-io # enter disqus shortname here

# Share
share: default # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    lightgallery: true # options: true, false
    google_analytics: UA-85661914-1 # enter the tracking ID for your Google Analytics
    baidu_analytics: # enter Baidu Analytics hash key

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
    links:
        "NonBlock": http://blog.javarouka.me/
        "CS Tech Blog": https://css-org.github.io/
