# Menus
menu:
    Post: 
        icon: pencil
        path: /
    About: 
        icon: user
        path: /about/index.html
    # pt: 
    #     icon: file-text
    #     path: /pt/index.html
    # toyproject: 
    #     icon: hashtag
    #     path: /toyproject/index.html

# Category
categories:

# Customize
customize:
    social_links: # for more icons, please see http://fontawesome.io/icons/#brand
        facebook: https://www.facebook.com/hanghui.i
        github: https://github.com/javarouka
        rss: /atom.xml

# Comment
comment:
    disqus: https-javarouka-github-io

# Plugins
plugins:
    google_analytics: UA-85661914-1

# Miscellaneous
miscellaneous:
    open_graph:
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
    links:
        "NonBlock": http://blog.javarouka.me/
        "CS Tech Blog": https://css-org.github.io/