name: Site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        npm install
        npm run deploy
