name: Site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: npm install
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: npm install
      run: npm run build
    - name: deploy
      uses: ad-m/github-push-action@some
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
